ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'NEWS_UPDATED';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'NEWS_DELETED';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'ALERT_CREATED';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'ALERT_UPDATED';
ALTER TYPE "InAppNotificationType" ADD VALUE IF NOT EXISTS 'ALERT_DELETED';
