export const ALERT_TYPES = {
  POWER_OUTAGE: 'POWER_OUTAGE',
  WATER_SUPPLY: 'WATER_SUPPLY',
  GAS_SUPPLY: 'GAS_SUPPLY',
  ROAD_ACCIDENT: 'ROAD_ACCIDENT',
  EMERGENCY: 'EMERGENCY',
  WEATHER: 'WEATHER',
  TECHNICAL_WORKS: 'TECHNICAL_WORKS',
  OTHER: 'OTHER',
} as const;

export const ALERT_SEVERITIES = {
  INFO: 'INFO',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
  EMERGENCY: 'EMERGENCY',
} as const;
