import { PERMISSIONS_KEYS } from './permissions.const';
import { ROLES } from './roles.const';

export const ALL_PERMISSIONS = Object.values(PERMISSIONS_KEYS);

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.ADMIN]: ALL_PERMISSIONS,

  [ROLES.MUNICIPALITY]: [
    PERMISSIONS_KEYS.CITY_REQUEST_UPDATE,
    PERMISSIONS_KEYS.CITY_REQUEST_MANAGE,
    PERMISSIONS_KEYS.REPORT_CREATE,
    PERMISSIONS_KEYS.REPORT_UPDATE,
    PERMISSIONS_KEYS.REPORT_MANAGE,
    PERMISSIONS_KEYS.ATTACHMENT_CREATE,
    PERMISSIONS_KEYS.CHAT_CREATE,
    PERMISSIONS_KEYS.CHAT_MANAGE,
    PERMISSIONS_KEYS.MESSAGE_CREATE,
    PERMISSIONS_KEYS.ALERT_CREATE,
    PERMISSIONS_KEYS.ALERT_UPDATE,
    PERMISSIONS_KEYS.ALERT_MANAGE,
    PERMISSIONS_KEYS.NEWS_CREATE,
    PERMISSIONS_KEYS.NEWS_UPDATE,
    PERMISSIONS_KEYS.NEWS_MANAGE,
    PERMISSIONS_KEYS.SURVEY_CREATE,
    PERMISSIONS_KEYS.SURVEY_UPDATE,
    PERMISSIONS_KEYS.SURVEY_MANAGE,
    PERMISSIONS_KEYS.COMMENT_CREATE,
    PERMISSIONS_KEYS.COMMENT_UPDATE,
  ],

  [ROLES.ORGANIZER]: [
    PERMISSIONS_KEYS.PROJECT_CREATE,
    PERMISSIONS_KEYS.PROJECT_UPDATE,
    PERMISSIONS_KEYS.PROJECT_DELETE,
    PERMISSIONS_KEYS.PROJECT_MANAGE,
    PERMISSIONS_KEYS.COMMENT_CREATE,
    PERMISSIONS_KEYS.COMMENT_UPDATE,
    PERMISSIONS_KEYS.COMMENT_DELETE,
    PERMISSIONS_KEYS.CITY_REQUEST_CREATE,
    PERMISSIONS_KEYS.ATTACHMENT_CREATE,
    PERMISSIONS_KEYS.MESSAGE_CREATE,
  ],

  [ROLES.CITIZEN]: [
    PERMISSIONS_KEYS.CITY_REQUEST_CREATE,
    PERMISSIONS_KEYS.REPORT_CREATE,
    PERMISSIONS_KEYS.ATTACHMENT_CREATE,
    PERMISSIONS_KEYS.CHAT_CREATE,
    PERMISSIONS_KEYS.MESSAGE_CREATE,
    PERMISSIONS_KEYS.VOTE_CREATE,
    PERMISSIONS_KEYS.DONATION_CREATE,
    PERMISSIONS_KEYS.COMMUNITY_CREATE,
    PERMISSIONS_KEYS.POST_CREATE,
    PERMISSIONS_KEYS.POST_UPDATE,
    PERMISSIONS_KEYS.POST_DELETE,
    PERMISSIONS_KEYS.COMMENT_CREATE,
    PERMISSIONS_KEYS.COMMENT_UPDATE,
    PERMISSIONS_KEYS.COMMENT_DELETE,
    PERMISSIONS_KEYS.REACTION_CREATE,
    PERMISSIONS_KEYS.REACTION_DELETE,
  ],
};
